services:
  web:
    container_name: osb-web
    build: .
    environment:
      DATABASE_URL: postgres://osb_user:osb_password@db:5432/osb_db
      BETTER_AUTH_SECRET: YOURBETTERAUTHSECRET # https://www.better-auth.com/docs/installation#set-environment-variables
      BETTER_AUTH_URL: http://localhost:3000 # The final URL where the app is hosted
      MICROSOFT_CLIENT_ID: MSID # alternatively use GitHub
      MICROSOFT_CLIENT_SECRET: MSSECRET
      MICROSOFT_TENANT_ID: MSTENANTID
      MICROSOFT_TEACHERS_GROUP_ID: MSTEACHERSGROUPID
      NEXT_PUBLIC_PDF_COMPANY: YOURCOMPANY
      NEXT_PUBLIC_PDF_SUBTITLE: YOURADDRESSORSIMILAR
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:17"
    environment:
      POSTGRES_USER: "osb_user"
      POSTGRES_PASSWORD: "osb_password"
      POSTGRES_DB: "osb_db"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
